ci: add codeclimate test report (#18)

diff --git a/.github/workflows/dev-cicd.yml b/.github/workflows/dev-cicd.yml
--- a/.github/workflows/dev-cicd.yml
+++ b/.github/workflows/dev-cicd.yml
@@ -158,7 +158,9 @@ jobs:
         run: pnpm install --frozen-lockfile
 
       - name: Unit Test Affected by Release
-        run: pnpm nx test ${{ matrix.projectName }} --codeCoverage
+        # Note: skip cache, otherwise tests will replay results from local machines
+        #       which results to incorrect coverage paths (local and ci paths are structured differently)
+        run: pnpm nx test ${{ matrix.projectName }} --codeCoverage --skip-nx-cache
 
       - name: Move shard coverage
         run: mv $(find coverage -name coverage-final.json) coverage/${{matrix.projectName}}.json
@@ -169,7 +171,36 @@ jobs:
           name: coverage-artifacts
           path: coverage/
 
-  # TODO: test report
+  test-report:
+    name: Test Report
+    runs-on: ubuntu-latest
+    needs: [create-pull-request, run-tests]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+          token: ${{ secrets.GA_PAT }}
+
+      - name: Download coverage from jest shards
+        uses: actions/download-artifact@v3
+        with:
+          name: coverage-artifacts
+          path: coverage
+
+      - name: Merge Code Coverage
+        run: npx nyc merge coverage/ merged-output/merged-coverage.json
+
+      - name: Generate coverage report
+        run: npx nyc report -t merged-output --report-dir merged-output --reporter lcov
+
+      - name: Upload coverage to codeclimate
+        uses: paambaati/codeclimate-action@v3.2.0
+        env:
+          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPORTER_ID }}
+        with:
+          coverageLocations: |
+            ${{github.workspace}}/merged-output/lcov.info:lcov
 
   chromatic:
     name: ${{ matrix.projectName }}
@@ -233,12 +264,16 @@ jobs:
   final-check:
     name: Final Check
     runs-on: ubuntu-latest
-    needs: [create-pull-request, run-tests, dev-deploy, chromatic]
-    if: |
-      always() &&
-      needs.create-pull-request.result == 'success' &&
-      needs.run-tests.result == 'success' &&
-      needs.dev-deploy.result == 'success' &&
-      needs.chromatic.result == 'success'
+    needs: [create-pull-request, test-report, dev-deploy, chromatic]
+    # Always run even any of needs was skipped/failed/canceled
+    if:
+      always()
+      # needs.*.result == 'success' &&
     steps:
+      - name: Fail on skipped/cancelled/failure
+        if: |
+          contains(needs.*.result, 'failure') ||
+          contains(needs.*.result, 'cancelled') ||
+          contains(needs.*.result, 'skipped')
+        run: exit 1
       - run: echo "All checks passed"
